### ISSUE TITLE
Fresh project build problem: Ubuntu + NVM

### ISSUE THREAD

**Issue by tajakobsen** [enonic/cli-enonic#346] opened 2022-01-26 12:22 UTC
I am unable to build a completely fresh project on **Ubuntu**.

I created the project using `enonic project create`, and selecting "React4xp starter".

I have installed *node* and *npm* trough [nvm](https://github.com/nvm-sh/nvm). Is this a problem for this starter?

Here is my log: 

```bash
tomaj@galilei:~/code/item/myproject$ enonic project build

Building in sandbox 'mysandbox'...

> Configure project :

Not found: node_modules/react4xp/react4xp.gradle - running shell command:
npm install

FAILURE: Build failed with an exception.

* Where:
Build file '/home/tomaj/code/item/myproject/build.gradle' line: 62

* What went wrong:
A problem occurred evaluating root project 'myproject'.
> Cannot run program "npm": error=2, No such file or directory

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

exit status 1
```

**Comment by alansemenov** [comment] 2022-04-08 08:52
Duplicate of https://github.com/enonic/cli-enonic/issues/345

**Closed by alansemenov** 2022-04-08 08:52 UTC
