### ISSUE TITLE
enonic cli error with git bash

### ISSUE THREAD

**Issue by poi33** [enonic/cli-enonic#394] opened 2023-03-30 14:27 UTC
![image](https://user-images.githubusercontent.com/3340349/228868446-f39cd6e7-d434-4d67-8f01-1b10848661db.png)

The gitbash seems to auto cancel with when its waiting for arrow function input.

**Comment by alansemenov** [comment] 2023-04-05 11:21
Looks like a duplicate of https://github.com/enonic/cli-enonic/issues/337

**Closed by alansemenov** 2023-04-05 11:21 UTC
Labels: Bug
